### ISSUE TITLE
MySQL can handle lowercase

### ISSUE THREAD

**Issue by R-K-H** [atenashad/jan-version#1]
https://github.com/atenashad/jan-version/blob/master/api-db.php#L8

You don't really need this as long as the sort order is an actual sort order, maybe consider if I passed the $order_way a string like "; DROP TABLE;" or something simple like "WOOHOOO" your program would fail as the MySQL query is invalid. You want to make sure your logic fails rather than the MySQL query. You can do this with a simple test (in you switch statement even) to make sure it's one or the other, if not fail. In the case of the DROP TABLE you'll have SQL injection which can be a big issue.

:) 👍

**Comment by atenashad** [comment]
can you explain what you mean a bit more? 
From what I understand atm, the concern arrives because there would be a possibility for user data being put into the SQL, but this gets handled because of the default so that even if anything else is passed it would default back to either ASC or DESC - no?

**Comment by R-K-H** [comment]
Gotcha. Yea the default case would be left to ASC. I see that in the case you reassign the variable either or.
